circuit_path = [
"benchmarks/VOQC_t/adder_8.qasm",
"benchmarks/VOQC_t/barenco_tof_10.qasm",
"benchmarks/VOQC_t/barenco_tof_3.qasm",
"benchmarks/VOQC_t/barenco_tof_4.qasm",
"benchmarks/VOQC_t/barenco_tof_5.qasm",
"benchmarks/VOQC_t/csla_mux_3.qasm",
"benchmarks/VOQC_t/csum_mux_9.qasm",
"benchmarks/VOQC_t/gf2^10_mult.qasm",
"benchmarks/VOQC_t/gf2^16_mult.qasm",
"benchmarks/VOQC_t/gf2^4_mult.qasm",
"benchmarks/VOQC_t/gf2^5_mult.qasm",
"benchmarks/VOQC_t/gf2^6_mult.qasm",
"benchmarks/VOQC_t/gf2^7_mult.qasm",
"benchmarks/VOQC_t/gf2^8_mult.qasm",
"benchmarks/VOQC_t/gf2^9_mult.qasm",
"benchmarks/VOQC_t/mod_mult_55.qasm",
"benchmarks/VOQC_t/mod_red_21.qasm",
"benchmarks/VOQC_t/mod5_4.qasm",
"benchmarks/VOQC_t/qcla_adder_10.qasm",
"benchmarks/VOQC_t/qcla_com_7.qasm",
"benchmarks/VOQC_t/qcla_mod_7.qasm",
"benchmarks/VOQC_t/rc_adder_6.qasm",
"benchmarks/VOQC_t/tof_10.qasm",
"benchmarks/VOQC_t/tof_3.qasm",
"benchmarks/VOQC_t/tof_4.qasm",
"benchmarks/VOQC_t/tof_5.qasm",
"benchmarks/VOQC_t/vbe_adder_3.qasm"]
omega = [6]
oracle_name = ["Quartz"]
ecc_path = ["resources/Clifford_T_5_3_complete_ECC_set.json"]
soam_cost = ["Mixed"]
quartz_cost = ["Mixed"]
timeout = ["1"]
gateset = ["CliffordT"]
n_threads = [64]