circuit_path = [
"benchmarks/Nam_rz/QFTAdd8.qasm",
"benchmarks/Nam_rz/QFTAdd16.qasm",
"benchmarks/Nam_rz/QFTAdd32.qasm",
"benchmarks/Nam_rz/QFTAdd64.qasm",
"benchmarks/Nam_rz/QFTAdd128.qasm",
"benchmarks/Nam_rz/QFTAdd256.qasm"
]
omega = [6]
oracle_name = ["Quartz"]
ecc_path = ["resources/Nam_5_3_complete_ECC_set.json"]
soam_cost = ["Mixed"]
quartz_cost = ["Mixed"]
timeout = ["1"]
gateset = ["Nam"]
n_threads = [64]