circuit_path = [
    "benchmarks/Jatin_rz/qft_n80_from_qiskit.qasm",
    "benchmarks/Jatin_rz/grover_n11_from_python.qasm",
    "benchmarks/Jatin_rz/vqe_n20_from_python.qasm",
    "benchmarks/Jatin_rz/hhl_n9_from_python.qasm"
]
omega = [6]
preprocess_omega=[6]
oracle_name = ["Quartz"]
ecc_path = ["resources/Nam_6_3_complete_ECC_set.json"]
soam_cost = ["Gate"]
quartz_cost = ["Gate"]
gateset = ["Nam"]
n_threads = [1]

[[timeout]]
PerSegment = 0.0