circuit_path = [
"benchmarks/nwqbench/medium/boolean_satisfaction_n28.qasm.transpiled",
"benchmarks/nwqbench/medium/grover_search_n23.qasm.transpiled",
"benchmarks/nwqbench/medium/multiplier_n60.qasm.transpiled",
"benchmarks/nwqbench/medium/square_root_n24.qasm.transpiled",
"benchmarks/nwqbench/medium/statevector_n5.qasm.transpiled",
"benchmarks/nwqbench/medium/vqc_n18.qasm.transpiled",
"benchmarks/nwqbench/medium/vqe_n10.qasm.transpiled",
]
omega = [10]
preprocess_omega = [30]
oracle_name = ["Quartz"]
ecc_path = ["resources/Nam_6_3_complete_ECC_set.json"]
soam_cost = ["Gate"]
quartz_cost = ["Gate"]
gateset = ["Nam"]
n_threads = [1]

[[timeout]]
PerSegment = 0.0