circuit_path = [
"benchmarks/nwqbench/small/boolean_satisfaction_n24.qasm.transpiled",
"benchmarks/nwqbench/small/grover_search_n19.qasm.transpiled",
"benchmarks/nwqbench/small/hhl_n7.qasm.transpiled",
"benchmarks/nwqbench/small/multiplier_n50.qasm.transpiled",
"benchmarks/nwqbench/small/square_root_n21.qasm.transpiled",
"benchmarks/nwqbench/small/statevector_n4.qasm.transpiled",
"benchmarks/nwqbench/small/vqc_n15.qasm.transpiled",
"benchmarks/nwqbench/small/vqe_n8.qasm.transpiled",
]
omega = [10]
preprocess_omega = [30]
oracle_name = ["Quartz"]
ecc_path = ["resources/Nam_6_3_complete_ECC_set.json"]
soam_cost = ["Mixed"]
quartz_cost = ["Mixed"]
gateset = ["Nam"]
n_threads = [1]

[[timeout]]
PerSegment = 0.0