circuit_path = [
     "${BENCHMARK_DIR}/nwq_statevector_n5/nwq_statevector_n5.qasm.preprocessed.new",
    "${BENCHMARK_DIR}/nwq_statevector_n6/nwq_statevector_n6.qasm.preprocessed.new",
    "${BENCHMARK_DIR}/nwq_statevector_n7/nwq_statevector_n7.qasm.preprocessed.new",
    "${BENCHMARK_DIR}/nwq_statevector_n8/nwq_statevector_n8.qasm.preprocessed.new",
]
use_soam = [true]
omega = [100]
preprocess_config = ["None"]
cost = ["Gate"]
gateset = ["Nam"]
n_threads = [256]
layout = ["Dense"]


[[oracle_name]]

[oracle_name.Quartz]
cost = "Gate"
ecc_path = "resources/Nam_5_3_complete_ECC_set.json"
gateset = "Nam"
n_threads = 256

[oracle_name.Quartz.timeout]
PerSegment = 2