circuit_path = [
    "${BENCHMARK_DIR}/shor_7_mod_15_n10_from_python/shor_7_mod_15_n10_from_python.qasm.preprocessed.new",
    "${BENCHMARK_DIR}/shor_7_mod_15_n12_from_python/shor_7_mod_15_n12_from_python.qasm.preprocessed.new",
    "${BENCHMARK_DIR}/shor_7_mod_15_n14_from_python/shor_7_mod_15_n14_from_python.qasm.preprocessed.new",
    "${BENCHMARK_DIR}/shor_7_mod_15_n16_from_python/shor_7_mod_15_n16_from_python.qasm.preprocessed.new",
]
use_soam = [true]
omega = [100]
preprocess_config = ["None"]
cost = ["Mixed"]
gateset = ["Nam"]
n_threads = [256]
layout = ["Dense"]


[[oracle_name]]

[oracle_name.Quartz]
cost = "Mixed"
ecc_path = "resources/Nam_5_3_complete_ECC_set.json"
gateset = "Nam"
n_threads = 256

[oracle_name.Quartz.timeout]
PerSegment = 2