circuit_path = [
    "${BENCHMARK_DIR}/nwq_boolean_satisfaction_n28/nwq_boolean_satisfaction_n28.qasm.preprocessed.new",
    "${BENCHMARK_DIR}/nwq_boolean_satisfaction_n30/nwq_boolean_satisfaction_n30.qasm.preprocessed.new",
    "${BENCHMARK_DIR}/nwq_boolean_satisfaction_n32/nwq_boolean_satisfaction_n32.qasm.preprocessed.new",
    "${BENCHMARK_DIR}/nwq_boolean_satisfaction_n34/nwq_boolean_satisfaction_n34.qasm.preprocessed.new",
]
use_soam = [true]
omega = [100]
preprocess_config = ["None"]
cost = ["Mixed"]
gateset = ["Nam"]
n_threads = [256]
layout = ["Dense"]


[[oracle_name]]

[oracle_name.Quartz]
cost = "Mixed"
ecc_path = "resources/Nam_5_3_complete_ECC_set.json"
gateset = "Nam"
n_threads = 256

[oracle_name.Quartz.timeout]
PerSegment = 2