circuit_path = [
    "${BENCHMARK_DIR}/nwq_boolean_satisfaction_n28/nwq_boolean_satisfaction_n28.qasm.preprocessed.new",
    "${BENCHMARK_DIR}/nwq_binary_welded_tree_n17/nwq_binary_welded_tree_n17.qasm.preprocessed.new",
    "${BENCHMARK_DIR}/grover_n9_from_python/grover_n9_from_python.qasm.preprocessed.new",
    "${BENCHMARK_DIR}/hhl_n7_from_python/hhl_n7_from_python.qasm.preprocessed.new",
    "${BENCHMARK_DIR}/shor_7_mod_15_n10_from_python/shor_7_mod_15_n10_from_python.qasm.preprocessed.new",
    "${BENCHMARK_DIR}/nwq_square_root_n42/nwq_square_root_n42.qasm.preprocessed.new",
    "${BENCHMARK_DIR}/nwq_statevector_n5/nwq_statevector_n5.qasm.preprocessed.new",
    "${BENCHMARK_DIR}/vqe_n12_from_python/vqe_n12_from_python.qasm.preprocessed.new",
]
use_soam = [true]
omega = [100]
preprocess_config = ["None"]
cost = ["Mixed"]
gateset = ["Nam"]
n_threads = [160]
layout = ["Dense"]


[[oracle_name]]

[oracle_name.Quartz]
cost = "Mixed"
ecc_path = "resources/Nam_5_3_complete_ECC_set.json"
gateset = "Nam"
n_threads = 160

[oracle_name.Quartz.timeout]
PerSegment = 2