circuit_path = [
    "benchmarks/Jatin_rz_RM/ham15-med.qasm",
]
omega = [6,10,15,20,25]
oracle_name = ["Quartz"]
ecc_path = ["resources/Nam_5_3_complete_ECC_set.json"]
soam_cost = ["Gate"]
quartz_cost = ["Gate"]
timeout = ["2","5","10","20"]
gateset = ["Nam"]
n_threads = [64]