circuit_path = [
    "benchmarks/Jatin_rz_RM/hhl_n7.qasm",
]
# omega = [6,10,15,20,25]
omega=[6]
oracle_name = ["Quartz"]
ecc_path = ["resources/Nam_5_3_complete_ECC_set.json"]
soam_cost = ["Gate"]
quartz_cost = ["Gate"]
# timeout = ["2","5","10","20"]
timeout=["0.5"]
gateset = ["Nam"]
n_threads = [64]