circuit_path = [
    "${BENCHMARK_DIR}/hhl_n13_from_python.qasm",
]
use_soam = [true]
omega = [200]
preprocess_config = ["None"]
cost = ["Gate"]
gateset = ["Nam"]
n_threads = [1]
layout = ["One"]


[[oracle_name]]

[oracle_name.Voqc]