circuit_path = [
    "${BENCHMARK_DIR}/nwq_boolean_satisfaction_n28.qasm",
    "${BENCHMARK_DIR}/nwq_binary_welded_tree_n17.qasm",
    "${BENCHMARK_DIR}/grover_n9_from_python.qasm",
    "${BENCHMARK_DIR}/hhl_n7_from_python.qasm",
    "${BENCHMARK_DIR}/shor_7_mod_15_n10_from_python.qasm",
    "${BENCHMARK_DIR}/nwq_square_root_n42.qasm",
    "${BENCHMARK_DIR}/nwq_statevector_n5.qasm",
    "${BENCHMARK_DIR}/vqe_n18_from_python.qasm",
]
use_soam = [true]
omega = [200]
preprocess_config = ["None"]
cost = ["Gate"]
gateset = ["Nam"]
n_threads = [64]
layout = ["One"]


[[oracle_name]]

[oracle_name.Tket]